version: '3.8'
services:
  db:
    image: postgres:12
    restart: always
    networks: [database]
    ports:
      - target: 5432
        published: 5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: proxify
    volumes:
      - type: volume
        source: pg-data
        target: /var/lib/postgresql/data
        consistency: delegated

  application:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on: [db]

volumes:
  pg-data:

networks:
  database: